-- Album: Kessoku Band Mix
-- Auto-generated by dfmp migration script

dfmpAlbum_KB = {
    id = "KB",
    title = "Kessoku Band Mix",
    trackSource = {
        soundPrefix = "dfmpKB",
        labels = {
            "01 Kessoku band - Distortion!!",
            "02 Kessoku band - Flashbacker",
            "03 Kessoku band - Guitar Loneliness and Blue Planet",
            "04 Kessoku band - Hitoribocchi Tokyo",
            "05 Kessoku band - I cant sing a love song",
            "06 Kessoku band - I wont forget",
            "07 Kessoku band - If I could become a constellation",
            "08 Kessoku band - Karakara",
            "09 Kessoku band - Rolling rock morning falls on you",
            "10 Kessoku band - Secret base",
            "11 Kessoku band - Seisyun Complex",
            "12 Kessoku band - That band",
            "13 Kessoku band - The little sea",
            "14 Kessoku band - What is wrong with"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "KBCassetteA",
                b = "KBCassetteB",
                containerEmpty = "KBCassetteCaseEmpty",
                containerFull = "KBCassetteCaseFull",
            },
            ranges = {
                a = { 1, 7 },
                b = { 8, 14 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "KBCDA",
                b = "KBCDB",
                containerEmpty = "KBCDCoverEmpty",
                containerFull = "KBCDCoverFull",
            },
            ranges = {
                a = { 1, 7 },
                b = { 8, 14 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover4",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

