-- Album: Random Mix Vol.1
-- Auto-generated by dfmp migration script

dfmpAlbum_Mix1 = {
    id = "Mix1",
    title = "Random Mix Vol.1",
    trackSource = {
        soundPrefix = "dfmpMix1",
        labels = {
            "01 Bandit Radio - STALKER OST",
            "02 Boom Boom Boom Boom",
            "03 Bunker Blues - METRO OST",
            "04 Celldweller - Shapeshifter",
            "05 Djo - End of Beginning",
            "06 Guns n Roses",
            "07 Jawny - Honeypie",
            "08 Komm Susser Tod",
            "09 Last Christmas",
            "10 Nightcore - Sweet Little Bumblebee",
            "11 Nirvana - Drain You",
            "12 PlayArrow - Chipi-Chipi-Chapa-Chapa",
            "13 Radiohead - No Suprises",
            "14 Radiohead - Electioneering",
            "15 Radiohead - Exit Music For a Film",
            "16 Reol+nqrse",
            "17 Roar of the Jungle Dragon"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "Mix1CassetteA",
                b = "Mix1CassetteB",
                containerEmpty = "Mix1CassetteCaseEmpty",
                containerFull = "Mix1CassetteCaseFull",
            },
            ranges = {
                a = { 1, 9 },
                b = { 10, 17 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "Mix1CDA",
                b = "Mix1CDB",
                containerEmpty = "Mix1CDCoverEmpty",
                containerFull = "Mix1CDCoverFull",
            },
            ranges = {
                a = { 1, 9 },
                b = { 10, 17 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover13",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

