-- Album: Anime Mix
-- Auto-generated by dfmp migration script

dfmpAlbum_Anime = {
    id = "Anime",
    title = "Anime Mix",
    trackSource = {
        soundPrefix = "dfmpAnime",
        labels = {
            "01 Baka Mitai",
            "02 Bloody Stream",
            "03 Crossing Field",
            "04 Dora Doradura",
            "05 Dororo",
            "06 Evangelion OST - Fly Me to the Moon",
            "07 Fukkireta",
            "08 Gurren Lagann - OP1",
            "09 Hai Yo",
            "10 Hello My World",
            "11 Kenshi Yonezu - KICK BACK",
            "12 Kuusou Mesorogiwi",
            "13 Peace Sign",
            "14 Renai Circulation",
            "15 Seishun Buta Yarou - Fukashigi no Carte",
            "16 Step",
            "17 Tank",
            "18 Tetrad smerti - OP1",
            "19 Tetrad smerti - Pianino",
            "20 The Day",
            "21 The Peggies - Kimi no Sei",
            "22 Tiny Light",
            "23 Viewtiful Days",
            "24 Wonderful Wonder World",
            "25 YOASOBI - IDOL",
            "26 Yoko Takahashi - A Cruel Angels Thesis",
            "27 Yume no Tsuzuki"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "AnimeCassetteA",
                b = "AnimeCassetteB",
                containerEmpty = "AnimeCassetteCaseEmpty",
                containerFull = "AnimeCassetteCaseFull",
            },
            ranges = {
                a = { 1, 14 },
                b = { 15, 27 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "AnimeCDA",
                b = "AnimeCDB",
                containerEmpty = "AnimeCDCoverEmpty",
                containerFull = "AnimeCDCoverFull",
            },
            ranges = {
                a = { 1, 14 },
                b = { 15, 27 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover5",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

