-- Album: Umamusume Mix
-- Auto-generated by dfmp migration script

dfmpAlbum_Uma = {
    id = "Uma",
    title = "Umamusume Mix",
    trackSource = {
        soundPrefix = "dfmpUma",
        labels = {
            "01 Umamusume - Bokura no burubadodeizu",
            "02 Umamusume - Egao no Treasure",
            "03 Umamusume - UNLIMITED IMPACT",
            "04 Umamusume 2 ED"
        },
    },
    media = {
        cassette = {
            mode = "full",
            items = {
                full = "UmaCassette",
                containerEmpty = "UmaCassetteCaseEmpty",
                containerFull = "UmaCassetteCaseFull",
            },
        },
        cd = {
            mode = "full",
            items = {
                full = "UmaCD",
                containerEmpty = "UmaCDCoverEmpty",
                containerFull = "UmaCDCoverFull",
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover8",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

