-- Album: Serega Pirat Mix Vol.2
-- Auto-generated by dfmp migration script

dfmpAlbum_SPVol2 = {
    id = "SPVol2",
    title = "Serega Pirat Mix Vol.2",
    trackSource = {
        soundPrefix = "dfmpSP2",
        labels = {
            "01 Serega Pirat - Nataliya",
            "02 Serega Pirat - Novogodnyaya",
            "03 Serega Pirat - Nu gde moya noga",
            "04 Serega Pirat - Nu i chto ya vor",
            "05 Serega Pirat - Pesnya afroamerikantsev",
            "06 Serega Pirat - Pesnya kitaytsev",
            "07 Serega Pirat - Pochemu ne fanat",
            "08 Serega Pirat - Rassel krou",
            "09 Serega Pirat - Tilt",
            "10 Serega Pirat - Tp na ame",
            "11 Serega Pirat - V Etoy Trave",
            "12 Serega Pirat - Vaybmen",
            "13 Serega Pirat - Vnutri menya voyna",
            "14 Serega Pirat - World of Dota",
            "15 Serega Pirat - Ya eto ya",
            "16 Serega Pirat - YA podnimayu golovu",
            "17 Serega Pirat - YA shizoid",
            "18 Serega Pirat - YA svoruyu babki",
            "19 Serega Pirat - Ya vzletayu",
            "20 Serega Pirat Barikader - kak zhe on silen"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "SPVol2CassetteA",
                b = "SPVol2CassetteB",
                containerEmpty = "SPVol2CassetteCaseEmpty",
                containerFull = "SPVol2CassetteCaseFull",
            },
            ranges = {
                a = { 1, 10 },
                b = { 11, 20 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "SPVol2CDA",
                b = "SPVol2CDB",
                containerEmpty = "SPVol2CDCoverEmpty",
                containerFull = "SPVol2CDCoverFull",
            },
            ranges = {
                a = { 1, 10 },
                b = { 11, 20 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover2",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

