-- Album: Serega Pirat Mix Vol.3
-- Auto-generated by dfmp migration script

dfmpAlbum_SPVol3 = {
    id = "SPVol3",
    title = "Serega Pirat Mix Vol.3",
    trackSource = {
        soundPrefix = "dfmpSP3",
        labels = {
            "01 Serega Pirat Kijin - Kartyni",
            "02 Serega Pirat Lida - CHSV",
            "03 Serega Pirat - Mutanty iz kanalizatsii",
            "04 Serega Pirat - Zombi apokalipsis",
            "05 Lida Serega Pirat - chsv",
            "06 mzlff Serega Pirat - YA ne boyus",
            "07 DronXD - Poslednij Bloudzhob",
            "08 Mayzenberg - vitalyu obmanul"
        },
    },
    media = {
        cassette = {
            mode = "full",
            items = {
                full = "SPVol3Cassette",
                containerEmpty = "SPVol3CassetteCaseEmpty",
                containerFull = "SPVol3CassetteCaseFull",
            },
        },
        cd = {
            mode = "full",
            items = {
                full = "SPVol3CD",
                containerEmpty = "SPVol3CDCoverEmpty",
                containerFull = "SPVol3CDCoverFull",
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover3",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

