-- Album: Russian Mix Vol.1
-- Auto-generated by dfmp migration script

dfmpAlbum_RU1 = {
    id = "RU1",
    title = "Russian Mix Vol.1",
    trackSource = {
        soundPrefix = "dfmpRU1",
        labels = {
            "01 Arthur Pirozhkov - Chica",
            "02 Arthur Pirozhkov - Ja zvezda!",
            "03 Arthur Pirozhkov - Ja ne Andrey",
            "04 Arthur Pirozhkov - KakCelentano",
            "05 KSB muzic - DEP",
            "06 KSB muzic - W YA vytacshu",
            "07 Mark Bernes - Temnaya noch",
            "08 MellSher and 5opka - Long Aylend",
            "09 Modern Talking - Cheri Cheri Lady",
            "10 Nervi - Poteri",
            "11 Nervi - to chto mne nuzno",
            "12 Potap i Nastya - CHumachechaya vesna",
            "13 Potap i Nastya - My otmenyaem konets sveta",
            "14 Sati Kazanova - Do Rassveta",
            "15 Sindrom Vosmiklassnika - Kerosin",
            "16 STINT - Eto ne moy vayb"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "RU1CassetteA",
                b = "RU1CassetteB",
                containerEmpty = "RU1CassetteCaseEmpty",
                containerFull = "RU1CassetteCaseFull",
            },
            ranges = {
                a = { 1, 8 },
                b = { 9, 16 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "RU1CDA",
                b = "RU1CDB",
                containerEmpty = "RU1CDCoverEmpty",
                containerFull = "RU1CDCoverFull",
            },
            ranges = {
                a = { 1, 8 },
                b = { 9, 16 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover10",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

