-- Album: Molchat Doma Mix
-- Auto-generated by dfmp migration script

dfmpAlbum_MD = {
    id = "MD",
    title = "Molchat Doma Mix",
    trackSource = {
        soundPrefix = "dfmpMD",
        labels = {
            "01 Filmy by Molchat Doma",
            "02 Kletka by Molchat Doma",
            "03 Kommersanty by Molchat Doma",
            "04 Molchat Doma - Emalirovannoe sudno",
            "05 Molchat Doma - Kletka V2",
            "06 Na Dne by Molchat Doma",
            "07 Prognoz by Molchat Doma",
            "08 Sudno by Molchat Doma",
            "09 Tantsevat by Molchat Doma",
            "10 Toska by Molchat Doma",
            "11 Volny by Molchat Doma"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "MDCassetteA",
                b = "MDCassetteB",
                containerEmpty = "MDCassetteCaseEmpty",
                containerFull = "MDCassetteCaseFull",
            },
            ranges = {
                a = { 1, 6 },
                b = { 7, 11 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "MDCDA",
                b = "MDCDB",
                containerEmpty = "MDCDCoverEmpty",
                containerFull = "MDCDCoverFull",
            },
            ranges = {
                a = { 1, 6 },
                b = { 7, 11 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover6",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

