-- Album: Russian Mix Vol.2
-- Auto-generated by dfmp migration script

dfmpAlbum_RU2 = {
    id = "RU2",
    title = "Russian Mix Vol.2",
    trackSource = {
        soundPrefix = "dfmpRU2",
        labels = {
            "01 Smetana Band - pit plakat",
            "02 Smetana band - kogda moya devushka kurit",
            "03 Uma2rman - Kazhetsya",
            "04 Uma2rman - Papiny dochki",
            "05 Valentin Strykalo - Nashe leto",
            "06 Valentin Strykalo - YA byu zhenshchin",
            "07 Virus - Poproshu tebya",
            "08 Visokosnyy god - Tihiy ogonek",
            "09 Volhey-Milo-materishsya",
            "10 YArche Solntsa Ne Hochu",
            "11 YUliya Savicheva - Esli v serdtse zhivet lyubov",
            "12 forestdump - Klanovaya zhizn",
            "13 pivzavod2077 - Fotografiruyu pivas",
            "14 konec-solnechnyh-dnej - finala-ne-budet",
            "15 ssshhhiiittt! - vosem"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "RU2CassetteA",
                b = "RU2CassetteB",
                containerEmpty = "RU2CassetteCaseEmpty",
                containerFull = "RU2CassetteCaseFull",
            },
            ranges = {
                a = { 1, 8 },
                b = { 9, 15 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "RU2CDA",
                b = "RU2CDB",
                containerEmpty = "RU2CDCoverEmpty",
                containerFull = "RU2CDCoverFull",
            },
            ranges = {
                a = { 1, 8 },
                b = { 9, 15 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover11",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

