-- Album: Sponge Bob Mix
-- Auto-generated by dfmp migration script

dfmpAlbum_SB = {
    id = "SB",
    title = "Sponge Bob Mix",
    trackSource = {
        soundPrefix = "dfmpSB",
        labels = {
            "01 Sponge Bob - Bytovuha OST 1",
            "02 Sponge Bob - Bytovuha OST 2",
            "03 Sponge Bob - Krasti Krabs OST 1",
            "04 Sponge Bob - Krasti Krabs OST 2",
            "05 Sponge Bob - Pogonya",
            "06 Sponge Bob - Titry",
            "07 Sponge Bob - Zastavka"
        },
    },
    media = {
        cassette = {
            mode = "full",
            items = {
                full = "SBCassette",
                containerEmpty = "SBCassetteCaseEmpty",
                containerFull = "SBCassetteCaseFull",
            },
        },
        cd = {
            mode = "full",
            items = {
                full = "SBCD",
                containerEmpty = "SBCDCoverEmpty",
                containerFull = "SBCDCoverFull",
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover12",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

