-- Album: Linkin Park
-- Auto-generated by dfmp migration script

dfmpAlbum_LP = {
    id = "LP",
    title = "Linkin Park",
    trackSource = {
        soundPrefix = "dfmpLP",
        labels = {
            "01 Blues For Mr T",
            "02 Bud Meets Bob",
            "03 Crawling - Linkin Park",
            "04 In the End - Linkin Park",
            "05 My December - Linkin Park",
            "06 Points of Authority - Linkin Park"
        },
    },
    media = {
        vinyl = {
            mode = "split",
            items = {
                a = "LPVinylA",
                b = "LPVinylB",
                containerEmpty = "LPJacketEmpty",
                containerFull = "LPJacketFull",
            },
            ranges = {
                a = { 1, 3 },
                b = { 4, 6 },
            },
        },
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover19_Vinyl",
            includePlayable = { "vinyl" },
            includeContainers = { "vinyl" },
        },
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover19_Vinyl_Empty",
            includeEmptyContainers = { "vinyl" },
        },
    },
}

