-- Album: Serega Pirat Mix Vol.1
-- Auto-generated by dfmp migration script

dfmpAlbum_SPVol1 = {
    id = "SPVol1",
    title = "Serega Pirat Mix Vol.1",
    trackSource = {
        soundPrefix = "dfmpSP1",
        labels = {
            "01 Serega Pirat - 911",
            "02 Serega Pirat - A ti",
            "03 Serega Pirat - AM FP",
            "04 Serega Pirat - Anime Opening",
            "05 Serega Pirat - Apelsin",
            "06 Serega Pirat - Dedoded",
            "07 Serega Pirat - dengimenyayut",
            "08 Serega Pirat - Geroin",
            "09 Serega Pirat - Gimn",
            "10 Serega Pirat - Gimn dahaka",
            "11 Serega Pirat - Heytery",
            "12 Serega Pirat - Izvini segodnya prazdnik",
            "13 Serega Pirat - Kachalka",
            "14 Serega Pirat - Kartiny",
            "15 Serega Pirat - Masha",
            "16 Serega Pirat - Moy bayk",
            "17 Serega Pirat - Moy slark",
            "18 Serega Pirat - Moy topor",
            "19 Serega Pirat - Ny izvinite",
            "20 Serega Pirat - Na lune"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "SPVol1CassetteA",
                b = "SPVol1CassetteB",
                containerEmpty = "SPVol1CassetteCaseEmpty",
                containerFull = "SPVol1CassetteCaseFull",
            },
            ranges = {
                a = { 1, 10 },
                b = { 11, 20 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "SPVol1CDA",
                b = "SPVol1CDB",
                containerEmpty = "SPVol1CDCoverEmpty",
                containerFull = "SPVol1CDCoverFull",
            },
            ranges = {
                a = { 1, 10 },
                b = { 11, 20 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover1",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

