-- Album: Sektor Gaza Mix
-- Auto-generated by dfmp migration script

dfmpAlbum_SG = {
    id = "SG",
    title = "Sektor Gaza Mix",
    trackSource = {
        soundPrefix = "dfmpSG",
        labels = {
            "01 Sektor Gaza - 30 let",
            "02 Sektor Gaza - Bomzh",
            "03 Sektor Gaza - Demobilizatsiya",
            "04 Sektor Gaza - Lirika",
            "05 Sektor Gaza - Pora domoy"
        },
    },
    media = {
        cassette = {
            mode = "full",
            items = {
                full = "SGCassette",
                containerEmpty = "SGCassetteCaseEmpty",
                containerFull = "SGCassetteCaseFull",
            },
        },
        cd = {
            mode = "full",
            items = {
                full = "SGCD",
                containerEmpty = "SGCDCoverEmpty",
                containerFull = "SGCDCoverFull",
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover9",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

