-- Album: Persona 3 Reload Mix
-- Auto-generated by dfmp migration script

dfmpAlbum_P3 = {
    id = "P3",
    title = "Persona 3 Reload Mix",
    trackSource = {
        soundPrefix = "dfmpP3",
        labels = {
            "01 Persona 3 Reload - Changing Seasons",
            "02 Persona 3 Reload - Full Moon Full Life",
            "03 Persona 3 Reload - Unavoidable Battle",
            "04 Persona 3 Reload - When The Moon Reaching Out Stars"
        },
    },
    media = {
        cassette = {
            mode = "full",
            items = {
                full = "P3Cassette",
                containerEmpty = "P3CassetteCaseEmpty",
                containerFull = "P3CassetteCaseFull",
            },
        },
        cd = {
            mode = "full",
            items = {
                full = "P3CD",
                containerEmpty = "P3CDCoverEmpty",
                containerFull = "P3CDCoverFull",
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover7",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

