-- Album: Random Mix Vol.2
-- Auto-generated by dfmp migration script

dfmpAlbum_Mix2 = {
    id = "Mix2",
    title = "Random Mix Vol.2",
    trackSource = {
        soundPrefix = "dfmpMix2",
        labels = {
            "01 Rock - I Am Rock",
            "02 Running in The 90s",
            "03 Sakura Ikimono Gakari",
            "04 Stormae - Alena Dast",
            "05 Stressed Glob",
            "06 Styles of Beyond - Nine Thou",
            "07 Surf Curse - Freaks",
            "08 Tell Me Why",
            "09 Tincup - Lost",
            "10 Tri Dnya Dozhdya - Otpuskay",
            "11 Tri Dnya Vozhdya - Otsosat",
            "12 Universal Collapse",
            "13 burning desires",
            "14 come alive",
            "15 fishing village rust",
            "16 iris-out",
            "17 yuanse"
        },
    },
    media = {
        cassette = {
            mode = "split",
            items = {
                a = "Mix2CassetteA",
                b = "Mix2CassetteB",
                containerEmpty = "Mix2CassetteCaseEmpty",
                containerFull = "Mix2CassetteCaseFull",
            },
            ranges = {
                a = { 1, 9 },
                b = { 10, 17 },
            },
        },
        cd = {
            mode = "split",
            items = {
                a = "Mix2CDA",
                b = "Mix2CDB",
                containerEmpty = "Mix2CDCoverEmpty",
                containerFull = "Mix2CDCoverFull",
            },
            ranges = {
                a = { 1, 9 },
                b = { 10, 17 },
            },
        }
    },
    coverGroups = {
        {
            mode = "linked",
            texture = "WorldItems/Vinyl/World_NM_Cover14",
            includePlayable = { "cassette", "cd" },
            includeContainers = { "cassette", "cd" },
            includeEmptyContainers = { "cassette", "cd" },
        },
    },
}

